### ISSUE TITLE
HorsePass doesn't inherit, therefore no super required

### ISSUE THREAD

**Issue by Helithumper** [HackUCF/OnboardLite#2]
https://github.com/HackUCF/OnboardLite/blob/main/util/horsepass.py#L31C19-L31C19 super call is not required as HorsePass does not inherit

**Comment by Helithumper** [comment]
https://github.com/HackUCF/OnboardLite/pull/3 fixed as part of this

**Comment by jeffreydivi** [comment]
There's also a typo. This has been fixed in a local commit of mine that will be pushed later today as a part of the Terraform integration.

**Comment by jeffreydivi** [comment]
Fixed.
